server.port: 8099

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

spring:
  application:
    name: forum-kotlin-api
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:h2:file:./data/my_database_flyway;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: false
      path: /h2-console